import React from 'react';

const GrammarTheoryDashboard = () => {
  return (
    <div style={{ maxWidth: '900px', margin: '0 auto' }}>

      {/* ── About Context-Free Grammar (CFG) ── */}
      <section style={{
        background: '#0A0A0A',
        border: '1px solid rgba(212, 225, 87, 0.12)',
        borderRadius: '20px',
        padding: 'clamp(1.5rem, 4vw, 2.5rem)',
        marginBottom: '3rem',
      }}>
        <h2 style={{
          fontSize: 'clamp(1.4rem, 3vw, 1.8rem)',
          fontWeight: 800,
          color: '#FFFFFF',
          marginBottom: '1.25rem',
          letterSpacing: '-0.03em',
          lineHeight: 1.2,
        }}>
          About Context-Free Grammar <span style={{ color: '#D4E157' }}>(CFG)</span>
        </h2>

        <p style={{
          color: '#A1A1A1',
          fontSize: '0.88rem',
          lineHeight: 1.8,
          marginBottom: '1.5rem',
        }}>
          A Context-Free Grammar is a fundamental structure in formal language theory, utilized
          mathematically to generate strings in a specific formal language. A standard CFG is
          formally defined as a 4-tuple{' '}
          <strong style={{ color: '#D4E157', fontFamily: "'JetBrains Mono', monospace" }}>
            G = (V, T, P, S)
          </strong>{' '}
          where:
        </p>

        <div style={{
          display: 'flex',
          flexDirection: 'column',
          gap: '10px',
          marginBottom: '2rem',
        }}>
          <TupleItem
            symbol="V"
            label="Variables / Non-terminals"
            desc="A finite, non-empty set of symbols representing syntactic categories or sub-trees in the language."
          />
          <TupleItem
            symbol="T"
            label="Terminals"
            desc="A finite, non-empty set of basic symbols from which the actual output strings are formed. By definition, variables and terminals must be disjoint sets (V ∩ T = ∅)."
          />
          <TupleItem
            symbol="P"
            label="Productions"
            desc="A finite set of production mapping rules taking the form A → α, where A is exactly one variable, and α is any continuous string composed of variables and/or terminals."
          />
          <TupleItem
            symbol="S"
            label="Start Symbol"
            desc="A specialized non-terminal serving as the immutable root of the grammar tree. All valid words generated by the language begin their derivation sequence from S."
          />
        </div>

        {/* Context-Free Designation */}
        <div style={{
          borderTop: '1px solid rgba(255,255,255,0.06)',
          paddingTop: '1.5rem',
        }}>
          <h3 style={{
            fontSize: '1rem',
            fontWeight: 700,
            color: '#FFFFFF',
            marginBottom: '0.75rem',
            letterSpacing: '-0.01em',
          }}>
            The "Context-Free" Designation
          </h3>
          <p style={{
            color: '#888888',
            fontSize: '0.85rem',
            lineHeight: 1.8,
          }}>
            The descriptor "context-free" originates purely from the production rules. In entirely
            context-free grammars, the left constraint of any production is strictly limited to an
            isolated, single Non-Terminal variable. This guarantees that whenever a grammar derives
            a string, any specific variable can instantly be recursively rewritten with its
            right-hand rule regardless of adjacent terminals—irrespective of its "context".
          </p>
        </div>
      </section>

      {/* ── About Simplification ── */}
      <section style={{
        background: '#0A0A0A',
        border: '1px solid rgba(255,255,255,0.06)',
        borderRadius: '20px',
        padding: 'clamp(1.5rem, 4vw, 2.5rem)',
        marginBottom: '2rem',
      }}>
        <h2 style={{
          fontSize: 'clamp(1.2rem, 2.5vw, 1.5rem)',
          fontWeight: 800,
          color: '#FFFFFF',
          marginBottom: '1rem',
          letterSpacing: '-0.02em',
        }}>
          Why <span style={{ color: '#D4E157' }}>Simplify</span> a Grammar?
        </h2>
        <p style={{
          color: '#888888',
          fontSize: '0.85rem',
          lineHeight: 1.8,
          marginBottom: '1.75rem',
        }}>
          Raw grammars often contain redundancies and artifacts that make parsing
          computationally expensive or outright impossible for certain algorithms.
          Simplification is a prerequisite for conversion to Chomsky Normal Form (CNF).
        </p>

        <div style={{
          display: 'flex',
          flexDirection: 'column',
          gap: '1px',
          background: 'rgba(212, 225, 87, 0.08)',
          borderRadius: '16px',
          overflow: 'hidden',
        }}>
          <PipelineStep
            step="01"
            title="Eliminate ε-Productions"
            desc="Identify all Nullable variables and generate the power-set of combinations, removing the need for empty string derivations."
            color="#F59E0B"
          />
          <PipelineStep
            step="02"
            title="Eliminate Unit Productions"
            desc="Collapse alias chains (A → B → C) by computing the derivation closure and substituting target rules directly."
            color="#60A5FA"
          />
          <PipelineStep
            step="03"
            title="Eliminate Useless Symbols"
            desc="Phase A: Bottom-up sweep to find non-generating symbols. Phase B: Top-down sweep to find unreachable symbols from Start."
            color="#F87171"
          />
          <PipelineStep
            step="04"
            title="Final Cleanup"
            desc="Remove duplicate productions and verify the grammar is in its simplest valid form."
            color="#34D399"
          />
        </div>
      </section>
    </div>
  );
};

const TupleItem = ({ symbol, label, desc }) => (
  <div style={{
    display: 'flex',
    gap: '14px',
    padding: '12px 14px',
    background: 'rgba(255,255,255,0.02)',
    borderRadius: '12px',
    transition: 'background 300ms ease',
  }}
  onMouseEnter={(e) => e.currentTarget.style.background = 'rgba(212, 225, 87, 0.04)'}
  onMouseLeave={(e) => e.currentTarget.style.background = 'rgba(255,255,255,0.02)'}
  >
    <span style={{
      flexShrink: 0,
      width: '36px',
      height: '36px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: '10px',
      background: 'rgba(212, 225, 87, 0.08)',
      border: '1px solid rgba(212, 225, 87, 0.2)',
      fontFamily: "'JetBrains Mono', monospace",
      fontWeight: 700,
      fontSize: '0.95rem',
      color: '#D4E157',
    }}>{symbol}</span>
    <div>
      <span style={{
        fontWeight: 700,
        color: '#FFFFFF',
        fontSize: '0.85rem',
      }}>{label}:</span>{' '}
      <span style={{
        color: '#888888',
        fontSize: '0.82rem',
        lineHeight: 1.7,
      }}>{desc}</span>
    </div>
  </div>
);

const PipelineStep = ({ step, title, desc, color }) => (
  <div style={{
    background: '#0A0A0A',
    padding: '1.25rem 1.5rem',
    transition: 'background 300ms ease',
    cursor: 'default',
  }}
  onMouseEnter={(e) => e.currentTarget.style.background = '#111111'}
  onMouseLeave={(e) => e.currentTarget.style.background = '#0A0A0A'}
  >
    <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '0.5rem' }}>
      <span style={{
        fontFamily: "'JetBrains Mono', monospace",
        fontSize: '0.65rem',
        fontWeight: 700,
        color: color,
        padding: '3px 8px',
        border: `1px solid ${color}33`,
        borderRadius: '6px',
        background: `${color}0F`,
      }}>{step}</span>
      <h4 style={{
        fontWeight: 700,
        color: '#FFFFFF',
        fontSize: '0.9rem',
        letterSpacing: '-0.01em',
      }}>{title}</h4>
    </div>
    <p style={{
      color: '#888888',
      fontSize: '0.8rem',
      lineHeight: 1.6,
      paddingLeft: '52px',
    }}>{desc}</p>
  </div>
);

export default GrammarTheoryDashboard;
